name: gocambio

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - server_db_data:/app
    networks:
      - challenge_net
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/cotacao || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - SERVER_URL=http://server:8080/cotacao
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client_output:/app
    networks:
      - challenge_net

networks:
  challenge_net:
    driver: bridge

volumes:
  server_db_data: